import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';
import { runInNewContext } from 'node:vm';
import { compileScript, parse } from '@vue/compiler-sfc';
import * as inertia from '@inertiajs/vue3';
import ts from 'typescript';
import * as vue from 'vue';

test('sidebar drag and keyboard moves save full order and restore it after cancelled or rejected requests', async t => {
    const { descriptor } = parse(readFileSync(new URL('../resources/js/components/WorkspaceSidebar.vue', import.meta.url), 'utf8'));
    const script = compileScript(descriptor, { id: 'sidebar-test' });
    const { outputText } = ts.transpileModule(script.content, { compilerOptions: { module: ts.ModuleKind.CommonJS } });
    const modules = { vue, '@inertiajs/vue3': inertia, '@/components/ui/sidebar': { useSidebar: () => ({ setOpenMobile() {} }) } };
    const context = { exports: {}, require: name => modules[name] ?? {} };
    runInNewContext(outputText, context);
    const requests = [];
    t.mock.method(inertia.router, 'put', (url, data, callbacks) => {
        callbacks.onStart();
        requests.push({ url, data, callbacks });
    });
    const props = vue.reactive({ projects: [{ id: 'alpha' }, { id: 'beta' }, { id: 'gamma' }], selectedProject: null, page: 'Dashboard' });
    const scope = vue.effectScope();
    t.after(() => scope.stop());
    const sidebar = scope.run(() => context.exports.default.setup(props, { expose() {} }));
    sidebar.saveOrder();
    assert.equal(requests.length, 0);
    sidebar.ordered.value.reverse();
    sidebar.saveOrder();
    sidebar.saveOrder();
    assert.equal(requests.length, 1);
    assert.equal(requests[0].url, '/projects/order');
    assert.deepEqual(Array.from(requests[0].data.ids), ['gamma', 'beta', 'alpha']);
    assert.equal(props.projects[0].id, 'alpha');
    requests[0].callbacks.onError({ ids: 'The project list changed.' });
    requests[0].callbacks.onFinish();
    assert.equal(sidebar.ordered.value[0].id, 'alpha');
    sidebar.move(0, 1);
    assert.deepEqual(Array.from(requests[1].data.ids), ['beta', 'alpha', 'gamma']);
    requests[1].callbacks.onCancel();
    requests[1].callbacks.onFinish();
    assert.equal(sidebar.ordered.value[0].id, 'alpha');
    sidebar.move(0, 1);
    props.projects = [props.projects[1], props.projects[0], props.projects[2]];
    await vue.nextTick();
    await requests[2].callbacks.onSuccess({});
    requests[2].callbacks.onFinish();
    assert.equal(sidebar.ordered.value[0].id, 'beta');
    assert.equal(sidebar.announcement.value, 'Project order saved.');
});
