import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';
import { runInNewContext } from 'node:vm';
import { compileScript, parse } from '@vue/compiler-sfc';
import * as inertia from '@inertiajs/vue3';
import ts from 'typescript';
import * as vue from 'vue';

test('sidebar status groups reorder only their own projects and save the full order', async t => {
    const { descriptor } = parse(readFileSync(new URL('../resources/js/components/WorkspaceSidebar.vue', import.meta.url), 'utf8'));
    const script = compileScript(descriptor, { id: 'sidebar-test' });
    const { outputText } = ts.transpileModule(script.content, { compilerOptions: { module: ts.ModuleKind.CommonJS } });
    const toasts = [];
    const modules = { vue, '@inertiajs/vue3': inertia, 'vue-sonner': { toast: { error: message => toasts.push(message) } }, '@/components/ui/sidebar': { useSidebar: () => ({ setOpenMobile() {} }) } };
    const context = { exports: {}, require: name => modules[name] ?? {} };
    runInNewContext(outputText, context);
    const requests = [];
    t.mock.method(inertia.router, 'put', (url, data, callbacks) => {
        callbacks.onStart();
        requests.push({ url, data, callbacks });
    });
    const props = vue.reactive({ projects: [{ id: 'alpha', name: 'Alpha', status: 'Idea' }, { id: 'live', name: 'Live site', status: 'Live' }, { id: 'beta', name: 'Beta', status: 'Idea' }, { id: 'gamma', name: 'Gamma', status: 'Live' }], selectedProject: null, page: 'Dashboard' });
    const scope = vue.effectScope();
    t.after(() => scope.stop());
    const sidebar = scope.run(() => context.exports.default.setup(props, { expose() {} }));
    assert.deepEqual(Array.from(sidebar.groups.value, group => group.status), ['Idea', 'Live']);
    assert.deepEqual(Array.from(sidebar.groups.value[0].projects, project => project.id), ['alpha', 'beta']);
    sidebar.projectQuery.value = '  beta ';
    assert.deepEqual(Array.from(sidebar.groups.value[0].projects, project => project.id), ['beta']);
    sidebar.reorderGroup('Idea', []);
    assert.deepEqual(Array.from(sidebar.ordered.value, project => project.id), ['alpha', 'live', 'beta', 'gamma']);
    sidebar.projectQuery.value = '';
    sidebar.saveOrder();
    assert.equal(requests.length, 0);
    sidebar.reorderGroup('Idea', [...sidebar.groups.value[0].projects].reverse());
    sidebar.saveOrder();
    sidebar.saveOrder();
    assert.equal(requests.length, 1);
    assert.equal(requests[0].url, '/projects/order');
    assert.deepEqual(Array.from(requests[0].data.ids), ['beta', 'live', 'alpha', 'gamma']);
    assert.equal(props.projects[0].id, 'alpha');
    requests[0].callbacks.onError({ ids: 'The project list changed.' });
    requests[0].callbacks.onFinish();
    assert.equal(sidebar.ordered.value[0].id, 'alpha');
    assert.deepEqual(toasts, ['Could not save project order. Reload and try again.']);
    sidebar.move('Idea', 0, 1);
    assert.deepEqual(Array.from(requests[1].data.ids), ['beta', 'live', 'alpha', 'gamma']);
    requests[1].callbacks.onCancel();
    requests[1].callbacks.onFinish();
    assert.equal(sidebar.ordered.value[0].id, 'alpha');
    sidebar.move('Idea', 1, 1);
    assert.equal(requests.length, 2);
    sidebar.move('Live', 0, 1);
    assert.deepEqual(Array.from(requests[2].data.ids), ['alpha', 'gamma', 'beta', 'live']);
    props.projects = [props.projects[0], props.projects[3], props.projects[2], props.projects[1]];
    await vue.nextTick();
    await requests[2].callbacks.onSuccess({});
    requests[2].callbacks.onFinish();
    assert.deepEqual(Array.from(sidebar.groups.value[1].projects, project => project.id), ['gamma', 'live']);
    assert.equal(sidebar.announcement.value, 'Project order saved.');
});
