<?php

use App\Http\Controllers\BackupController;
use App\Http\Controllers\BoardController;
use App\Http\Controllers\CatalogController;
use App\Http\Controllers\InspectionController;
use App\Http\Controllers\ProjectAssetController;
use App\Http\Controllers\ProjectDocumentController;
use App\Http\Controllers\ProviderController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\SecretController;
use App\Http\Controllers\SecretVaultController;
use App\Http\Controllers\WorkspaceController;
use App\Http\Middleware\RequireSecretUnlock;
use Illuminate\Support\Facades\Route;

Route::get('/', [WorkspaceController::class, 'index'])->name('workspace');
Route::get('/search', [SearchController::class, 'index'])->name('search');
Route::get('/projects/create', [WorkspaceController::class, 'create'])->name('projects.create');
Route::put('/projects/order', [WorkspaceController::class, 'reorder'])->name('projects.reorder');
Route::get('/projects/{project}', [WorkspaceController::class, 'show'])->name('projects.show');
Route::get('/projects/{project}/edit', [WorkspaceController::class, 'edit'])->name('projects.edit');
Route::post('/projects', [WorkspaceController::class, 'store'])->name('projects.store');
Route::post('/projects/{project}/duplicate', [WorkspaceController::class, 'duplicate'])->name('projects.duplicate');
Route::put('/projects/{project}', [WorkspaceController::class, 'update'])->name('projects.update');
Route::put('/projects/{project}/scratchpad', [WorkspaceController::class, 'updateScratchpad'])->name('projects.scratchpad.update');
Route::post('/projects/{project}/scratchpad/actions/preview', [WorkspaceController::class, 'previewScratchpadActions'])->middleware('throttle:6,1')->name('projects.scratchpad.actions.preview');
Route::post('/projects/{project}/scratchpad/actions', [WorkspaceController::class, 'applyScratchpadActions'])->name('projects.scratchpad.actions.apply');
Route::delete('/projects/{project}', [WorkspaceController::class, 'destroy'])->name('projects.destroy');
Route::put('/projects/{project}/documents', [ProjectDocumentController::class, 'update'])->name('projects.documents.update');
Route::post('/projects/{project}/documents/preview', [ProjectDocumentController::class, 'preview'])->name('projects.documents.preview');
Route::put('/projects/{project}/board', [BoardController::class, 'update'])->name('projects.board.update');
Route::post('/projects/{project}/inspection', [InspectionController::class, 'refresh'])->name('projects.inspection.refresh');
Route::post('/projects/{project}/roots', [InspectionController::class, 'roots'])->name('projects.roots.update');
Route::post('/projects/{project}/roots/{root}/outdated', [InspectionController::class, 'outdated'])->name('projects.roots.outdated');
Route::post('/projects/{project}/assets', [ProjectAssetController::class, 'store'])->name('projects.assets.store');
Route::put('/projects/{project}/assets/{asset}', [ProjectAssetController::class, 'move'])->name('projects.assets.move');
Route::post('/projects/{project}/asset-folders', [ProjectAssetController::class, 'saveFolder'])->name('projects.asset-folders.store');
Route::put('/projects/{project}/asset-folders/{folder}', [ProjectAssetController::class, 'saveFolder'])->name('projects.asset-folders.update');
Route::delete('/projects/{project}/asset-folders/{folder}', [ProjectAssetController::class, 'destroyFolder'])->name('projects.asset-folders.destroy');
Route::get('/projects/{project}/assets/{asset}', [ProjectAssetController::class, 'download'])->name('projects.assets.download');
Route::get('/projects/{project}/assets/{asset}/preview', [ProjectAssetController::class, 'download'])->name('projects.assets.preview');
Route::delete('/projects/{project}/assets/{asset}', [ProjectAssetController::class, 'destroy'])->name('projects.assets.destroy');
Route::post('/projects/{project}/board/preview', [BoardController::class, 'preview'])->name('projects.board.preview');
Route::post('/projects/{project}/secrets', [SecretController::class, 'store'])->middleware(RequireSecretUnlock::class)->name('projects.secrets.store');
Route::get('/secrets/unlock/status', [SecretVaultController::class, 'status'])->name('secrets.unlock.status');
Route::post('/secrets/pin', [SecretVaultController::class, 'setup'])->name('secrets.pin.store');
Route::post('/secrets/unlock', [SecretVaultController::class, 'unlock'])->name('secrets.unlock');
Route::post('/secrets/lock', [SecretVaultController::class, 'lock'])->name('secrets.lock');
Route::get('/projects/{project}/secrets/values', [SecretVaultController::class, 'values'])->middleware(RequireSecretUnlock::class)->name('projects.secrets.values');
Route::post('/projects/{project}/secrets/paste', [SecretController::class, 'paste'])->middleware(RequireSecretUnlock::class)->name('projects.secrets.paste');
Route::put('/projects/{project}/secrets/bulk', [SecretController::class, 'bulkMetadata'])->middleware(RequireSecretUnlock::class)->name('projects.secrets.bulk');
Route::post('/projects/{project}/secrets/import/preview', [SecretController::class, 'previewImport'])->middleware(RequireSecretUnlock::class)->name('projects.secrets.import.preview');
Route::post('/projects/{project}/secrets/import', [SecretController::class, 'import'])->middleware(RequireSecretUnlock::class)->name('projects.secrets.import');
Route::post('/projects/{project}/secrets/export/preview', [SecretController::class, 'previewExport'])->middleware(RequireSecretUnlock::class)->name('projects.secrets.export.preview');
Route::post('/projects/{project}/secrets/export', [SecretController::class, 'export'])->middleware(RequireSecretUnlock::class)->name('projects.secrets.export');
Route::put('/projects/{project}/secrets/{secret}', [SecretController::class, 'replace'])->middleware(RequireSecretUnlock::class)->name('projects.secrets.replace');
Route::put('/projects/{project}/secrets/{secret}/metadata', [SecretController::class, 'updateMetadata'])->middleware(RequireSecretUnlock::class)->name('projects.secrets.metadata');
Route::delete('/projects/{project}/secrets/{secret}', [SecretController::class, 'destroy'])->middleware(RequireSecretUnlock::class)->name('projects.secrets.destroy');
Route::get('/projects/{project}/secrets/{secret}/value', [SecretController::class, 'reveal'])->middleware(RequireSecretUnlock::class)->name('projects.secrets.reveal');
Route::post('/projects/{project}/secrets/{secret}/copy', [SecretController::class, 'copy'])->middleware(RequireSecretUnlock::class)->name('projects.secrets.copy');
Route::delete('/projects/{project}/secrets/{secret}/copy', [SecretController::class, 'clearClipboard'])->name('projects.secrets.copy.clear');
Route::get('/projects/{project}/tasks/{task}/attachments/{attachment}', [BoardController::class, 'download'])->name('projects.tasks.attachments.download');
Route::get('/projects/{project}/icon', [CatalogController::class, 'icon'])->name('projects.icon');
Route::post('/folders/inspect', [CatalogController::class, 'inspect'])->name('folders.inspect');
Route::post('/projects/{project}/open/{kind}/{id}', [CatalogController::class, 'open'])
    ->whereIn('kind', ['folders', 'repositories', 'links', 'secrets'])->name('projects.open');

Route::get('/settings/connections', [WorkspaceController::class, 'connections'])->name('connections.index');
Route::get('/settings/backups', [WorkspaceController::class, 'backups'])->name('backups.index');
Route::post('/backups/export/preview', [BackupController::class, 'previewExport'])->name('backups.export.preview');
Route::post('/backups/export', [BackupController::class, 'export'])->name('backups.export');
Route::post('/backups/restore/preview', [BackupController::class, 'previewRestore'])->name('backups.restore.preview');
Route::post('/backups/restore', [BackupController::class, 'applyRestore'])->name('backups.restore');
Route::post('/connections', [ProviderController::class, 'save'])->name('connections.store');
Route::get('/connections/{connection}/repositories', [ProviderController::class, 'repositories'])->name('connections.repositories');
Route::put('/connections/{connection}', [ProviderController::class, 'save'])->name('connections.update');
Route::delete('/connections/{connection}', [ProviderController::class, 'destroy'])->name('connections.destroy');
Route::post('/projects/{project}/repositories/{repository}/connection', [ProviderController::class, 'associate'])->name('repositories.connection');
Route::post('/projects/{project}/repositories/{repository}/refresh', [ProviderController::class, 'refresh'])->name('repositories.refresh');
